export const ErrorCode = {
  PROMPT_REQUIRED: "PROMPT_REQUIRED",
  INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_PACKAGE: "INVALID_PACKAGE",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  FAILED_TO_CREATE_ORDER: "FAILED_TO_CREATE_ORDER",
  FAILED_TO_CREATE_GENERATION: "FAILED_TO_CREATE_GENERATION",
  FAILED_TO_DELETE_TASK: "FAILED_TO_DELETE_TASK",
  CANNOT_DELETE_TASK: "CANNOT_DELETE_TASK",
  INVALID_REFERENCE_IMAGE: "INVALID_REFERENCE_IMAGE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
